### ISSUE TITLE
Cannot connect to Instagram via Facebook

### ISSUE THREAD

**Issue by localhorst** [verbb/social-feeds#3]
### Describe the bug

Following the integration guide for Instagram, I can't connect to Facebook because I only see a blank white page. (Step 2: Connect to Instagram)

### Steps to reproduce

1. I am working in a local development environment (DDEV) 
2. I set up a source for Instagram in the plugin settings. 
3. I set up the app in the Facebook Developers area
4. I entered the app ID and the app secret into the source fields
5. I saved the Instagram source 
6. I clicked on the connect button and was forwarded to a URL like this: "https://www.facebook.com/v15.0/dialog/oauth?scope=pages_show_list%2Cinstagram_basic%2Cinstagram_manage_comments%2Cpages_read_engagement&state=xxxxxxxxxxxxxxxxx&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Fmysite.ddev.site%2Fsocial-feeds%2Fauth%2Fcallback&client_id=xxxxxxxxxxxx#provider"
7. On this page, I cannot continue because it's just a blank page titled "Login with Facebook" / "Mit Facebook anmelden" 

### Craft CMS version

Craft Pro 4.3.3

### Plugin version

1.0.1

### Multi-site?

No

### Additional context

Only happened on local dev system.

**Comment by engram-design** [comment]
Anything on your `storage/logs/social-feeds.log` file? There probably won't be, but worth checking just in case. 

If you're stuck on the Facebook page, I've seen that before actually. If you inspect the page, you should even see the login form to login to Facebook, it's just hidden. I haven't exactly figured out _why_ it does this and shows a white screen instead. It eventually "just worked" after a while.

As per the [docs](https://verbb.io/craft-plugins/social-feeds/docs/providers/instagram) I'll assume their Instagram account is linked to a Facebook Page? Do you have access to that Facebook page?

**Comment by localhorst** [comment]
Thanks @engram-design , I managed to get a visible container by removing the "content-visibility: hidden;" (Chrome) or "display: none;" (Firefox) style of the first child div inside the body. 

The container shows this message now:
`Can't load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.`

I then added all my dev-, staging- and live-domains and I hope I'll get one step further once facebook has them properly processed. 

PS: Something I realized is that the connect url contains "v15.0" while my app is set for API-Version v16.0 (and I can't downgrade). I can change the url manually, but I get the same output. 

PPS: 

> Do you have access to that Facebook page?

Yes, I have.

**Comment by engram-design** [comment]
The API version shouldn't matter too much, I believe it will automatically be pinned to the lowest your app supports.

I'll mention that the domains will need to be HTTPS and that'll need to be able to be resolved correctly on your local install. That's mostly for the redirect URI, but I've seen this exact error come up for the domain for the same reason.

**Comment by localhorst** [comment]
I finally managed to connect my source by playing around with the settings in Facebook. I guess what made the change was one of these two steps in my app settings at developers.facebook.com:

1. Facebook Login > Settings: Enter all my dev, staging and live OAuth-URLs
2. Facebook Login > Settings: Disable Client OAuth Login (Set to _No_)

However, I can't tell what exactly made the change. I guess disabling the Facebook Login did it because it removed an authorization layer from the OAuth cycle. 

I also think the documentation provided by Facebook is a mess. I got some hints from this Stackoverflow post: https://stackoverflow.com/a/51846816/283854

Thanks for your help! I am closing this issue.

**Comment by engram-design** [comment]
Thanks for reporting! I'll spin up a new example from scratch just to double check I haven't missed anything in the docs.

**Comment by BAM-Dennis** [comment]
hey, same issue here,

doing this helped and solved the problem:
> 1. Facebook Login > Settings: Enter all my dev, staging and live OAuth-URLs

maybe add a step to the tutorial page.

**Comment by localhorst** [comment]
I still had the same trouble again when connecting the production system to Facebook. When playing around with the setting, this hint helped:

> Add a trailing slash to the callback URLs in the Facebook settings.
> The settings to adjust are located here https://developers.facebook.com/apps/[your_app_itentifier]/fb-login/.
> The trailing slash is important. They must match in your app code and in FB admin settings. 

https://stackoverflow.com/a/46932732/283854

**Comment by localhorst** [comment]
Closing this issue.
