### ISSUE TITLE
typo in docs

### ISSUE THREAD

**Issue by BAM-Dennis** [verbb/social-feeds#4]
### Describe the bug

There is a typo in your docs:

```
... 
{% set source = craft.socialFeeds.getSoureByHandle('mySourceHandle') %}
```

a c is missing ->
``` 
{% set source = craft.socialFeeds.getSourceByHandle('mySourceHandle') %}
``` 

### Steps to reproduce

1. 
2. 

### Craft CMS version

4.4.9

### Plugin version

1.0.1

### Multi-site?

yes

**Comment by engram-design** [comment]
Updated!
