### ISSUE TITLE
Cant generate Test User for Instagram Feed

### ISSUE THREAD

**Issue by iuscare** [verbb/social-feeds#9]
### Question

Hey,

I have successfully integrated a Facebook source into my project. Now, I'm looking to incorporate an Instagram source as well, with the goal of displaying content from both platforms within a unified feed.

The guidance provided in the documentation indicates that one should navigate to the "Instagram Testers" section and select the "Add Instagram Testers" button. However, I've encountered an issue where this action cannot be completed. Specifically, Meta responds with an error stating, "The option is currently not available." I'm seeking clarification on whether this step is essential for integrating an Instagram feed into my project. Additionally, I would like to know if there are any alternative solutions or workarounds to bypass this obstacle.

Kind Regards,
Pascal

**Comment by engram-design** [comment]
So that step is vital to accessing data, as otherwise to access another users Instagram data, you would need your Meta app to go through review and approval.

Looks like Meta have changed things again, as I'm now getting that error. Looks like it may be a [Meta](https://developers.facebook.com/community/threads/404528698927412/) issue, but will investigate.

**Comment by angelokeirsebilck** [comment]
I'm reading posts adding the tester should work again? I'm researching if I can replace https://plugins.craftcms.com/instagramfeed?craft4= with this plugin (mainly for Instagram, but also for Facebook) but need to be sure it is working.

I could test this myself but seems like a hassle to just test it. Could you test this @engram-design ?

Thanks in advance!

**Comment by iuscare** [comment]
@angelokeirsebilck tried this immediately after your reply. However, I can't confirm as I'm still unable to generate a test user. Maybe there are country-specific restrictions in place? I attempted this from Germany.

**Comment by engram-design** [comment]
So looks like I can add an Instagram tester to my app now! @iuscare are you still getting that same error message?

**Comment by engram-design** [comment]
Notably, Meta seems to just keep changing things! I've revised the docs _again_ with instructions that are working on my end at least. They revolve around business apps now https://verbb.io/craft-plugins/social-feeds/docs/providers/instagram

Let me know if you're still having issues connecting to Instagram.
